name: 'Continuous Delivery'
on:
  workflow_run:
    workflows: ["Continuous Integration"] 
    types:
      - completed
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
      GOOGLE_PROJECT: ${{ secrets.PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Install Gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: docker build --tag "$DOCKER_TAG" .

      - name: Push Docker image
        run: docker push "$DOCKER_TAG"
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy mle-challenge \
            --image ${{ env.DOCKER_TAG }} \
            --platform managed \
            --region ${{ secrets.REGION }} \
            --service-account ${{ secrets.SERVICE_ACCOUNT }} \
            --port 8000 \
            --allow-unauthenticated \
            --min-instances 1