name: 'Continuous Delivery'

on:
  workflow_run:
    workflows: ["Continuous Integration"] 
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Install Gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.PROJECT_ID }}
        run: |
          DOCKER_TAG="${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"