name: 'Continuous Integration'

on:
    pull_request:
        branches:
            [main, develop]
    push:
        branches:
            [main, develop]

    # Allow manual triggering of the workflow
    workflow_dispatch:

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with: 
                python-version: "3.10.18"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements-test.txt

            - name: Test App Code
              run: |
                make model-test
                make api-test

            - name: Format (formats code for readability)
              run: |
                black .

            - name: Lint (checks for bad code style)
              run: |
                pylint --disable=R,C  challenge/api.py